### PR TITLE
Modification, for accepting other types of plugins as mod_

### PR DESCRIPTION
**Pull request by lukascelinak**
I needed to implemetn recompletion for report, which is tracking completion and completion notifications, 
i think this modification is usable for local plugins too, because lot of them are storing data about users and their completion.

### CODE REVIEW

**Comment by danmarsden** [comment]
thanks @lukascelinak - I hadn't thought about needing to support other plugin types... I think if we do this we should rename the function and some of the variables in there from "activities" to plugins - eg "local_recompletion_get_supported_activities" should be "local_recompletion_get_supported_plugins" - are you able to re-organise that a bit? - if not, no worries I'll try to get to it at some point.

**Comment by lukascelinak** [comment]
> thanks @lukascelinak - I hadn't thought about needing to support other plugin types... I think if we do this we should rename the function and some of the variables in there from "activities" to plugins - eg "local_recompletion_get_supported_activities" should be "local_recompletion_get_supported_plugins" - are you able to re-organise that a bit? - if not, no worries I'll try to get to it at some point.

Hi Dan, yes no problem, I will make updates.

**Comment by lukascelinak** [comment]
Hi Dan, I builded improwements, I maked manual tests too. 
Best regards.

**Comment by danmarsden** [comment]
thanks - yeah that looks a lot cleaner - I'll try to test this soon and merge it.

**Comment by danmarsden** [comment]
Thanks @lukascelinak - looks good - merged it in.

**Pull request merged**
