### PR TITLE
Upgrade to code to improve recompletion options

### PR DESCRIPTION
**Pull request by adamrobertbacon**
Upgraded code to allow deletion/archive of the following data
- Current Grade Data (Not History)
- Quiz Data
- SCORM Data
To allow a course to be fully reset for recompletion.
Email notification is now optional/configurable and HTML compatible.

### CODE REVIEW

**Comment by danmarsden** [comment]
Thanks Adam - looks like some nice improvements - do you think we need to retain a copy of the grade_grades table though? - isn't that already covered by the core grade_grades_history table? - what would we need to keep a copy of that for?

**Comment by adamrobertbacon** [comment]
That's true, I hadn't really thought of it. Was just playing it safe and archiving anything that I was removing. I could remove that requirement. Other than that, you think its good enough?

**Comment by danmarsden** [comment]
I haven't had a chance to have a proper look yet, hoping to do that very soon though - thanks!

**Comment by adamrobertbacon** [comment]
Awesome, thanks. This is my first foray into the world of moodle/open source programming! I will work on removing the grade archive facility (as you say it's probably a waste of time), then I might see if I can work out how the backup stuff works.

**Comment by danmarsden** [comment]
cool - if you get a chance - keep an eye on the Travis builds - see the "details" link above - mainly the stuff triggered by moodle-plugin-ci codechecker - particularly any errors and warnings that are introduced by your code - (usually really easy fixes)

**Comment by danmarsden** [comment]
Hi Adam, do you think you will have time to keep looking at this? - if not can you please let me know and I'll see if I can find time to take what you've done so far and improve it further etc. Thanks!

**Comment by adamrobertbacon** [comment]
Hi Dan,
Learning and growing! Been a little busy with life the last week or 2 (3 small kids do that to you!) but I've done most of removing the bits required and fixing the code issues listed. Was looking to add Lesson type reset too as I think this is the only other category that would come under the category of recompletion. I have also redesigned the admin page and hidden most of the options in an advanced section so only those who are bothered will go to look at more options. I have been thinking about the grade_grades table and maybe if someone made a mistake they may wish to restore it, is it worth leaving in? It just means they have peace of mind that nothing is actually deleted. It also makes the advanced section of the admin page look a little more sensible as there are the same amount of delete options to archive options. They can always disable it! :)
Best Regards
Adam

**Comment by adamrobertbacon** [comment]
Hi Dan,
I have removed the grade_grades backup (still not sure about that) and tidied up the admin page. I haven't had a chance to look at Lesson type yet but that's next on my list. Please have a look and let me know what you think,
Best Regards

Adam

**Comment by danmarsden** [comment]
I've finally merged this in - just reverted a change to the task where you changed it to run every minute (probably to help with local testing.) - in normal usage of this plugin we should only need to run the task once a day. under normal usage of the plugin I can't see anyone having to repeat a specific course multiple times in a day! - if that does occur site admins can modify the default timing to suit.

thanks heaps!

**Pull request merged**
